<?php

namespace ContainerFClphGx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M5Drp17Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M5Drp17' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M5Drp17'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AlbumController::delete' => ['privates', '.service_locator.NjPUcEU', 'get_ServiceLocator_NjPUcEUService', true],
            'App\\Controller\\AlbumController::edit' => ['privates', '.service_locator.NjPUcEU', 'get_ServiceLocator_NjPUcEUService', true],
            'App\\Controller\\AlbumController::index' => ['privates', '.service_locator.NdJj..9', 'get_ServiceLocator_NdJj__9Service', true],
            'App\\Controller\\AlbumController::show' => ['privates', '.service_locator.NjPUcEU', 'get_ServiceLocator_NjPUcEUService', true],
            'App\\Controller\\ContactoController::delete' => ['privates', '.service_locator.uFGJTWo', 'get_ServiceLocator_UFGJTWoService', true],
            'App\\Controller\\ContactoController::edit' => ['privates', '.service_locator.uFGJTWo', 'get_ServiceLocator_UFGJTWoService', true],
            'App\\Controller\\ContactoController::index' => ['privates', '.service_locator.c4.HrsT', 'get_ServiceLocator_C4_HrsTService', true],
            'App\\Controller\\ContactoController::show' => ['privates', '.service_locator.uFGJTWo', 'get_ServiceLocator_UFGJTWoService', true],
            'App\\Controller\\ControllerAlbums::productos' => ['privates', '.service_locator._nRHRBM', 'get_ServiceLocator_NRHRBMService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.aBDcNeU', 'get_ServiceLocator_ABDcNeUService', true],
            'App\\Controller\\SecurityLoginController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.hEwcf7A', 'get_ServiceLocator_HEwcf7AService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.hEwcf7A', 'get_ServiceLocator_HEwcf7AService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.FXD6KYr', 'get_ServiceLocator_FXD6KYrService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.hEwcf7A', 'get_ServiceLocator_HEwcf7AService', true],
            'App\\Controller\\addController::index' => ['privates', '.service_locator._nRHRBM', 'get_ServiceLocator_NRHRBMService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\AlbumController:delete' => ['privates', '.service_locator.NjPUcEU', 'get_ServiceLocator_NjPUcEUService', true],
            'App\\Controller\\AlbumController:edit' => ['privates', '.service_locator.NjPUcEU', 'get_ServiceLocator_NjPUcEUService', true],
            'App\\Controller\\AlbumController:index' => ['privates', '.service_locator.NdJj..9', 'get_ServiceLocator_NdJj__9Service', true],
            'App\\Controller\\AlbumController:show' => ['privates', '.service_locator.NjPUcEU', 'get_ServiceLocator_NjPUcEUService', true],
            'App\\Controller\\ContactoController:delete' => ['privates', '.service_locator.uFGJTWo', 'get_ServiceLocator_UFGJTWoService', true],
            'App\\Controller\\ContactoController:edit' => ['privates', '.service_locator.uFGJTWo', 'get_ServiceLocator_UFGJTWoService', true],
            'App\\Controller\\ContactoController:index' => ['privates', '.service_locator.c4.HrsT', 'get_ServiceLocator_C4_HrsTService', true],
            'App\\Controller\\ContactoController:show' => ['privates', '.service_locator.uFGJTWo', 'get_ServiceLocator_UFGJTWoService', true],
            'App\\Controller\\ControllerAlbums:productos' => ['privates', '.service_locator._nRHRBM', 'get_ServiceLocator_NRHRBMService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.aBDcNeU', 'get_ServiceLocator_ABDcNeUService', true],
            'App\\Controller\\SecurityLoginController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.hEwcf7A', 'get_ServiceLocator_HEwcf7AService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.hEwcf7A', 'get_ServiceLocator_HEwcf7AService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.FXD6KYr', 'get_ServiceLocator_FXD6KYrService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.hEwcf7A', 'get_ServiceLocator_HEwcf7AService', true],
            'App\\Controller\\addController:index' => ['privates', '.service_locator._nRHRBM', 'get_ServiceLocator_NRHRBMService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\AlbumController::delete' => '?',
            'App\\Controller\\AlbumController::edit' => '?',
            'App\\Controller\\AlbumController::index' => '?',
            'App\\Controller\\AlbumController::show' => '?',
            'App\\Controller\\ContactoController::delete' => '?',
            'App\\Controller\\ContactoController::edit' => '?',
            'App\\Controller\\ContactoController::index' => '?',
            'App\\Controller\\ContactoController::show' => '?',
            'App\\Controller\\ControllerAlbums::productos' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityLoginController::login' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Controller\\addController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AlbumController:delete' => '?',
            'App\\Controller\\AlbumController:edit' => '?',
            'App\\Controller\\AlbumController:index' => '?',
            'App\\Controller\\AlbumController:show' => '?',
            'App\\Controller\\ContactoController:delete' => '?',
            'App\\Controller\\ContactoController:edit' => '?',
            'App\\Controller\\ContactoController:index' => '?',
            'App\\Controller\\ContactoController:show' => '?',
            'App\\Controller\\ControllerAlbums:productos' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityLoginController:login' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Controller\\addController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
