<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFClphGx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFClphGx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFClphGx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFClphGx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFClphGx\App_KernelDevDebugContainer([
    'container.build_hash' => 'FClphGx',
    'container.build_id' => 'a372268a',
    'container.build_time' => 1607503873,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFClphGx');
