<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJctBVtR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJctBVtR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJctBVtR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJctBVtR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJctBVtR\App_KernelDevDebugContainer([
    'container.build_hash' => 'JctBVtR',
    'container.build_id' => '704ae0fd',
    'container.build_time' => 1606209770,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJctBVtR');
