<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBcDOEjf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBcDOEjf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBcDOEjf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBcDOEjf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBcDOEjf\App_KernelDevDebugContainer([
    'container.build_hash' => 'BcDOEjf',
    'container.build_id' => '8a91510a',
    'container.build_time' => 1607440118,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBcDOEjf');
